# Manual-check items (not covered by this harness — self-verify, discussed in review):
#   - README explains: what this is, key design decision (graph storage, broadcast-grad reduction), how to run.
#   - A runnable XOR example exists using only Tensor + a hand-written SGD loop.
#   - Repo is clean: no dead code, no leftover commented-out experiments.
#
# Do not edit this file. If the Tensor interface genuinely needs to change, raise it — don't work around it here.

import numpy as np
import pytest
import torch

from tape import Tensor

TOL = 1e-6


def assert_close(actual, expected, tol=TOL):
    actual = np.asarray(actual, dtype=np.float64)
    expected = np.asarray(expected, dtype=np.float64)
    assert actual.shape == expected.shape, f"shape mismatch: {actual.shape} vs {expected.shape}"
    assert np.allclose(actual, expected, atol=tol, rtol=tol), f"\ngot:\n{actual}\nexpected:\n{expected}"


# ---------------------------------------------------------------------------
# Numeric correctness vs. torch oracle
# ---------------------------------------------------------------------------

def test_scalar_add_mul_matches_torch():
    a_np, b_np = np.array(2.0), np.array(3.0)

    a, b = Tensor(a_np, requires_grad=True), Tensor(b_np, requires_grad=True)
    c = a * b + b
    c.backward()

    ta = torch.tensor(a_np, requires_grad=True)
    tb = torch.tensor(b_np, requires_grad=True)
    tc = ta * tb + tb
    tc.backward()

    assert_close(c.data, tc.detach().numpy())
    assert_close(a.grad, ta.grad.numpy())
    assert_close(b.grad, tb.grad.numpy())


def test_broadcast_add_matches_torch():
    a_np = np.random.randn(4, 3)
    b_np = np.random.randn(3)  # broadcasts against a's rows

    a, b = Tensor(a_np, requires_grad=True), Tensor(b_np, requires_grad=True)
    c = (a + b).sum()
    c.backward()

    ta = torch.tensor(a_np, requires_grad=True)
    tb = torch.tensor(b_np, requires_grad=True)
    tc = (ta + tb).sum()
    tc.backward()

    assert_close(a.grad, ta.grad.numpy())
    assert_close(b.grad, tb.grad.numpy())  # this is the reduction case: (3,) grad from a (4,3) broadcast


def test_broadcast_mul_matches_torch():
    a_np = np.random.randn(5, 1)
    b_np = np.random.randn(1, 4)

    a, b = Tensor(a_np, requires_grad=True), Tensor(b_np, requires_grad=True)
    c = (a * b).sum()
    c.backward()

    ta = torch.tensor(a_np, requires_grad=True)
    tb = torch.tensor(b_np, requires_grad=True)
    tc = (ta * tb).sum()
    tc.backward()

    assert_close(a.grad, ta.grad.numpy())
    assert_close(b.grad, tb.grad.numpy())


def test_matmul_two_layer_matches_torch():
    x_np = np.random.randn(8, 6)
    w1_np = np.random.randn(6, 10)
    w2_np = np.random.randn(10, 2)

    x = Tensor(x_np, requires_grad=False)
    w1, w2 = Tensor(w1_np, requires_grad=True), Tensor(w2_np, requires_grad=True)
    out = ((x @ w1).relu() @ w2).sum()
    out.backward()

    tx = torch.tensor(x_np)
    tw1 = torch.tensor(w1_np, requires_grad=True)
    tw2 = torch.tensor(w2_np, requires_grad=True)
    tout = (torch.relu(tx @ tw1) @ tw2).sum()
    tout.backward()

    assert_close(w1.grad, tw1.grad.numpy())
    assert_close(w2.grad, tw2.grad.numpy())


def test_sum_axis_matches_torch():
    a_np = np.random.randn(4, 5)

    a = Tensor(a_np, requires_grad=True)
    c = a.sum(axis=1).sum()
    c.backward()

    ta = torch.tensor(a_np, requires_grad=True)
    tc = ta.sum(dim=1).sum()
    tc.backward()

    assert_close(a.grad, ta.grad.numpy())


def test_diamond_dependency_matches_torch():
    a_np, b_np = np.random.randn(3, 3), np.random.randn(3, 3)

    a, b = Tensor(a_np, requires_grad=True), Tensor(b_np, requires_grad=True)
    c = a * b
    d = a + b
    e = (c * d).sum()
    e.backward()

    ta, tb = torch.tensor(a_np, requires_grad=True), torch.tensor(b_np, requires_grad=True)
    tc = ta * tb
    td = ta + tb
    te = (tc * td).sum()
    te.backward()

    assert_close(a.grad, ta.grad.numpy())
    assert_close(b.grad, tb.grad.numpy())


def test_exp_log_matches_torch():
    a_np = np.abs(np.random.randn(4)) + 0.1  # keep log() domain-safe

    a = Tensor(a_np, requires_grad=True)
    c = a.exp().log().sum()
    c.backward()

    ta = torch.tensor(a_np, requires_grad=True)
    tc = ta.exp().log().sum()
    tc.backward()

    assert_close(a.grad, ta.grad.numpy())


# ---------------------------------------------------------------------------
# Behavioral correctness
# ---------------------------------------------------------------------------

def test_repeated_backward_accumulates():
    a = Tensor(np.array(3.0), requires_grad=True)
    b = a * a  # d/da = 2a = 6
    b.backward()
    b.backward()  # no zero_grad in between
    assert_close(a.grad, np.array(12.0))  # accumulated: 6 + 6


def test_zero_grad_then_fresh_forward_is_correct():
    a = Tensor(np.array(3.0), requires_grad=True)
    b = a * a
    b.backward()
    assert_close(a.grad, np.array(6.0))

    a.zero_grad()
    a.data = np.array(5.0)  # mutate leaf, recompute forward from scratch
    c = a * a
    c.backward()
    assert_close(a.grad, np.array(10.0))  # d/da = 2a = 10, not stale from first pass


def test_deep_chain_no_recursion_error():
    x = Tensor(np.array(1.0), requires_grad=True)
    y = x
    for _ in range(1000):
        y = y + 1.0
    try:
        y.backward()
    except RecursionError:
        pytest.fail("backward() on a 1000-op chain hit Python's recursion limit — use an iterative topo sort")
    assert_close(x.grad, np.array(1.0))
